### ISSUE TITLE
Error with Tinfoil (Nintendo Switch NSP Installer)

### ISSUE THREAD

**Issue by Migushthe2nd** [andresoviedo/google-drive-ftp-adapter#35]
An NSP Installer for the Nintendo Switch has support for ftp servers, and allows downloading from them. I connected it to the adapter server, but for some reason it cannot download. I can download fine from it via my computer.
Here a log:
https://pastebin.com/NsmjwHD5
I'm sorry, this could be a problem in the Tinfoil Installer, but it is just using a standard way of connecting.

**Comment by Migushthe2nd** [comment]
Also this:
`java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at org.apache.ftpserver.impl.IODataConnection.transfer(IODataConnection.java:289)
        at org.apache.ftpserver.impl.IODataConnection.transferToClient(IODataConnection.java:161)
        at org.apache.ftpserver.command.impl.RETR.execute(RETR.java:166)
        at org.apache.ftpserver.impl.DefaultFtpHandler.messageReceived(DefaultFtpHandler.java:210)
        at org.apache.ftpserver.listener.nio.FtpHandlerAdapter.messageReceived(FtpHandlerAdapter.java:61)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:716)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
        at org.apache.ftpserver.listener.nio.FtpLoggingFilter.messageReceived(FtpLoggingFilter.java:85)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
        at org.apache.mina.filter.logging.MdcInjectionFilter.filter(MdcInjectionFilter.java:136)
        at org.apache.mina.filter.util.CommonEventFilter.messageReceived(CommonEventFilter.java:70)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
        at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:427)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:245)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:434)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:46)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:796)
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:75)
        at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:780)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:772)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:714)
        at java.lang.Thread.run(Thread.java:748)
2018-11-13 17:52:13,480 WARN  pool-4-thread-26 PassivePorts         - Releasing unreserved passive port: 52485
2018-11-13 17:52:13,480 INFO  pool-4-thread-26 FtpLoggingFilter     - SENT: 150 File status okay; about to open data connection.

2018-11-13 17:52:13,480 INFO  pool-4-thread-26 FtpLoggingFilter     - RECEIVED: ABOR
2018-11-13 17:52:13,480 INFO  pool-4-thread-26 FtpLoggingFilter     - SENT: 426 Data connection error.

2018-11-13 17:52:13,480 INFO  pool-4-thread-26 FtpLoggingFilter     - SENT: 226 ABOR command successful.

2018-11-13 17:52:13,486 INFO  pool-4-thread-27 FtpLoggingFilter     - RECEIVED: QUIT
2018-11-13 17:52:13,487 INFO  pool-4-thread-27 FtpLoggingFilter     - SENT: 221 Goodbye.
`

**Comment by Migushthe2nd** [comment]
In the DZ Tinfoil app it logs: 
"network error: transfer closed with ********* bytes remaining to read
Failed to read pfs0 header!"

**Comment by Migushthe2nd** [comment]
Ok I think I know why this happends. Tinfoil is expecting to receive some information about the file 'immediatly' (that's why some small files did work) but the adapter first downloads the file and then sends it (right?). For big files this is a problem.
