### ISSUE TITLE
FTP Client in Nintendo Switch Console ERROR

### ISSUE THREAD

**Issue by fan3k** [andresoviedo/google-drive-ftp-adapter#42]
Why not download in my switch console? Look in error
![2](https://user-images.githubusercontent.com/46594950/51028481-c8844c00-1593-11e9-9e45-97b7dadb5427.jpg)
![1](https://user-images.githubusercontent.com/46594950/51028483-c8844c00-1593-11e9-81c9-5583fc009b72.jpg)

**Comment by andresoviedo** [comment]
@fan3k please test ftp adapter installation by accesing from your PC before trying from Nintendo .
If you still have problems please check log for errors.  
Regard

**Comment by JaySea77** [comment]
What ftp client on the switch are you using?
When I use sx installer I can browse, but cannot open any files.

**Comment by andresoviedo** [comment]
Hello @fan3k .  Did you succeed connecting your Nintendo to the FTP Adapter?
Plase close this issue if that's the case
Kind regards

**Comment by Vepox** [comment]
I am having the same exact problem. However, I think this problem is not caused by this project, as accessing the files through other FTP clients works flawless

**Comment by Vepox** [comment]
Nevermind. If I use the Filezilla FTP Server it does work. Issue probably is also related to the google drive ftp adapter.

**Comment by andresoviedo** [comment]
Thank you @vepox
You are certainly right
Every FTP client connect in a slightly different way to server.
I have no Switch console.
If you want however to call contribute fixing that, it would be required you to send the complete gdfa log to debug the issue.
Kind regards

**Comment by Vepox** [comment]
https://pastebin.com/3kXa83vX

**Comment by andresoviedo** [comment]
Hi @Vepox 

According the the logs, it look like the Nintendo Switch is closing the connection when downloading the file after 13 seconds.   At this right point, the app is doing nothing except transferring the file from Google to your Switch.

Do you have issues with all the files or just "Second Run RETURNS [01004D1007926000][v0].nsp"?
Do you have any timeout setting configured in your Nintendo Switch?

Kind regards

`Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: RECEIVED: EPSV
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: SENT: 229 Entering Passive Mode (|||54615|)
 
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: RECEIVED: TYPE I
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: SENT: 200 Command TYPE okay.
 
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: RECEIVED: SIZE 10 Second Run RETURNS [01004D1007926000][v0].nsp
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: SENT: 213 41084680
 
Feb 21, 2019 5:47:26 PM org.apache.ftpserver.listener.nio.FtpLoggingFilter info
INFORMATION: RECEIVED: RETR 10 Second Run RETURNS [01004D1007926000][v0].nsp
Feb 21, 2019 5:47:26 PM org.andresoviedo.google_drive_ftp_adapter.controller.Controller createInputStream
INFORMATION: Downloading file 1a6z9R4_5SIiQPrWJ-ZiRBbk7D8kmlee9...
Feb 21, 2019 5:47:26 PM org.andresoviedo.google_drive_ftp_adapter.model.GoogleDrive downloadFile
INFORMATION: Downloading file '1a6z9R4_5SIiQPrWJ-ZiRBbk7D8kmlee9'...
Feb 21, 2019 5:47:27 PM org.andresoviedo.google_drive_ftp_adapter.model.GoogleDrive downloadFile
INFORMATION: Download file... '1a6z9R4_5SIiQPrWJ-ZiRBbk7D8kmlee9
Feb 21, 2019 5:47:40 PM org.apache.ftpserver.impl.IODataConnection warn
WARNUNG: Exception during data transfer, closing data connection socket
java.net.SocketException: Connection reset by peer: socket write error
       at java.net.SocketOutputStream.socketWrite0(Native Method)
       at java.net.SocketOutputStream.socketWrite(Unknown Source)
       at java.net.SocketOutputStream.write(Unknown Source)
       at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
       at java.io.BufferedOutputStream.write(Unknown Source)
       at org.apache.ftpserver.impl.IODataConnection.transfer(IODataConnection.java:289)
       at org.apache.ftpserver.impl.IODataConnection.transferToClient(IODataConnection.java:161)
       at org.apache.ftpserver.command.impl.RETR.execute(RETR.java:169)`

**Comment by Vepox** [comment]
I have this issue with every file I try to download.
Cannot change the timeout settings

**Comment by fan3k** [comment]
Look for google-ocamlfuse

śr., 27 lut 2019, 17:26 użytkownik Vepox <notifications@github.com> napisał:
